joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

ur5_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  gains:
    waist: {p: 200.0, i: 10.0, d: 10.0, i_clamp: 1}
    shoulder: {p: 200.0, i: 10.0, d: 10.0, i_clamp: 1}
    elbow: {p: 200.0, i: 10.0, d: 10.0, i_clamp: 1}
    wrist_angle: {p: 200.0, i: 10.0, d: 10.0, i_clamp: 1}
    wrist_rotate: {p: 200.0, i: 10.0, d: 10.0, i_clamp: 1}
    gripper: {p: 200.0, i: 10.0, d: 10.0, i_clamp: 1}



d_finger_controller:
  type: position_controllers/JointPositionController
  joint: finger_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
u_finger_controller:
  type: position_controllers/JointPositionController
  joint: right_outer_knuckle_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
left_inner_finger_controller:
  type: position_controllers/JointPositionController
  joint: left_inner_knuckle_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
left_finger_controller:
  type: position_controllers/JointPositionController
  joint: left_inner_finger_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
right_inner_finger_controller:
  type: position_controllers/JointPositionController
  joint: right_inner_knuckle_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
right_finger_controller:
  type: position_controllers/JointPositionController
  joint: right_inner_finger_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
